05_blog_overview/03_fix_long_texts_displayed_in_full/learning_log/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('learning_logs.urls')),
]

05_blog_overview/03_fix_long_texts_displayed_in_full/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path
from . import views


app_name = 'learning_logs'

urlpatterns = [
    # homepage
    path('', views.index, name='index'),
    # topics
    path('topics/', views.topics, name='topics'),
    # entries
    path('topics/<int:pk>/', views.entry, name='entry'),
]

05_blog_overview/03_fix_long_texts_displayed_in_full/learning_logs/models.py
from django.db import models


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Something specific learned about a Topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text

05_blog_overview/03_fix_long_texts_displayed_in_full/learning_logs/views.py
from django.shortcuts import render
from .models import Topic, Entry


# Create your views here.
def index(request):
    """The home page for learning logs."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Displays a list of all available topics."""
    topics = Topic.objects.order_by('-date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def entry(request, pk):
    """Displays the full text of a a learning entry."""
    entry = Entry.objects.get(pk=pk)
    return render(request, 'learning_logs/entry.html')
    

05_blog_overview/03_fix_long_texts_displayed_in_full/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Log</title>
</head>
<body>
    <nav>
        <a href="{% url 'learning_logs:index' %}">Learning Logs</a>
        <a href="{% url 'learning_logs:topics' %}">All Topics</a>
    </nav>
    {% block content %}
    
    {% endblock %}
</body>
</html>

05_blog_overview/03_fix_long_texts_displayed_in_full/learning_logs/templates/learning_logs/entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    
    <h1>Learning Entry</h1>

    <a href="{% url 'learning_logs:topics' %}">Back</a>

{% endblock %}

05_blog_overview/03_fix_long_texts_displayed_in_full/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <h1>Learning Log</h1>
    <p>This app helps you keep track of what you're learning about.</p>

{% endblock %}

05_blog_overview/03_fix_long_texts_displayed_in_full/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
    
    <h1>Topics</h1>

    <ul>
    {% for topic in topics %}
        <li>{{ topic }}</li>

        <ul>
            {% for entry in topic.entry_set.all %}
                <li><a href="{% url 'learning_logs:entry' entry.id %}">{{ entry.text }}</a></li>
            {% empty %}
                <li>No logs for this topic.</li>
            {% endfor %}
        </ul>

    {% empty %}
        <li>No topics added yet</li>
    {% endfor %}
    </ul>

{% endblock %}