06_blog_detail/01_fix_capturing_path_components/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
]

06_blog_detail/01_fix_capturing_path_components/projects/urls.py
from django.urls import path
from . import views


app_name = 'projects'

urlpatterns = [
    path('', views.index, name='projects'),
    path('/?', views.detail, name='project_detail'),
]

06_blog_detail/01_fix_capturing_path_components/projects/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)

06_blog_detail/01_fix_capturing_path_components/projects/views.py
from django.shortcuts import render
from .models import Project


def index(request):
    projects = Project.objects.all()
    return render(request, 'projects/index.html', {'projects': projects})


def detail(request):
    project = Project.objects.get(pk=100)
    return render(request, 'projects/detail.html', {'project': project})

06_blog_detail/01_fix_capturing_path_components/projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'projects:projects' %}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'projects:projects' %}">Home</a>
            </li>
          </ul>
        </div>
    </div>

</nav>

<div class="container">
{% block content %}

{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

06_blog_detail/01_fix_capturing_path_components/projects/templates/projects/detail.html
{% extends "projects/base.html" %}
{% load static %}

{% block content %}

    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="https://via.placeholder.com/150" alt="{{ project.description }}" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project</h5>
            <p>{{ project.description }}</p>
            <h5>Built with:</h5>
            <p>{{ project.technology }}</p>
        </div>
    </div>

{% endblock %}

06_blog_detail/01_fix_capturing_path_components/projects/templates/projects/index.html
{% extends "projects/base.html" %}
{% load static %}
{% block content %}

    <h1>Projects</h1>
    <div class="row">
    {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description }}</p>
                    <a href="{% url 'projects:project_detail' %}" class="btn btn-primary">Read More</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}